// app/layout.js
import { Exo, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Existing Geist fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Exo font
const exo = Exo({
  variable: "--font-exo",
  subsets: ["latin"],
  weight: ["100","200","300","400","500","600","700","800","900"], // all weights
});

export const metadata = {
  title: "Yonn",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${exo.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
